### ISSUE TITLE
Provide documentation for building and running fenix, from source

### ISSUE THREAD

**Issue by ajmas** [coreybutler/fenix#84]
I noticed there wasn't really a recipe for building and running fenix from source, in case there are developers who want to help contribute. 

So far I have tried, based on current GitHu project:

   - Clone fenix project
   - change directory to `src`
   - run: `npm install` 
   - run: `npm install nw` 
   - Run `./node_modules/.bin/nw .`

This results in:

```
[0824/101117.707412:WARNING:chrome_main_delegate.cc(590)] final extension: 
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3 
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4 
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 5 
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 6 
extensions::schemaUtils:34
      throw new Error(message);
      ^

Error: Invalid value for argument 2. Property 'toolbar': Unexpected property, Property 'new-instance': Unexpected property.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:116:3)
    at Object.<anonymous> (extensions::binding:414:30)
    at chrome-extension://lbhapdancabnkhdlhgdhojedjbpcckeg/lib/controller/bootstrap.js:90:29
[20763:775:0824/101119.205532:ERROR:CONSOLE(1)] "Uncaught ReferenceError: DevToolsAPI is not defined", source:  (1)
[20763:775:0824/101119.206477:ERROR:CONSOLE(1)] "Uncaught ReferenceError: DevToolsAPI is not defined", source:  (1)
```

I then tried doing a symbolic link, such that fenix.nw -> src, this then gives me:

```
[0824/101405.524629:WARNING:chrome_main_delegate.cc(590)] final extension: .nw
[20952:35331:0824/101405.750623:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
```

Based on that error, I then tried `./node_modules/.bin/nw --disable-gpu ../fenix.nw`, which gives me:

```
[0824/101857.836747:WARNING:chrome_main_delegate.cc(590)] final extension: 
extensions::schemaUtils:34
      throw new Error(message);
      ^

Error: Invalid value for argument 2. Property 'toolbar': Unexpected property, Property 'new-instance': Unexpected property.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:116:3)
    at Object.<anonymous> (extensions::binding:414:30)
    at chrome-extension://lbhapdancabnkhdlhgdhojedjbpcckeg/lib/controller/bootstrap.js:90:29
[21141:775:0824/101858.901299:ERROR:CONSOLE(1)] "Uncaught ReferenceError: DevToolsAPI is not defined", source:  (1)
[21141:775:0824/101858.901366:ERROR:CONSOLE(1)] "Uncaught ReferenceError: DevToolsAPI is not defined", source:  (1)
```

Any suggestions would be appreciated. Also, it may be worth adding a 'scripts' section with a 'start' target in the package.json?

**Comment by coreybutler** [comment]
We're not going to pursue this since Fenix 3 is done and will be released very soon (we're putting the final touches on the websites now). It's a complete rewrite, so contributions to Fenix 2 would not be compatible with Fenix 3.
